### ISSUE TITLE
Feature Request:  Add check for length to check for lengths that are > 200

### ISSUE THREAD

**Issue by elimillera** [atorus-research/xportr#147]
### Feature Idea

`xportr_length`, values greater than 200 should not be allowed

**Comment by bms63** [comment]
@kaz462 this is the one you are working on??

**Comment by kaz462** [comment]
> @kaz462 this is the one you are working on??

https://github.com/atorus-research/xportr/pull/194 is for checking the variable length from data, this issue is for checking the length from spec/metadata in `xportr_length`

maybe another PR to resolve this issue? along with the following comment from @cpiraux : mention "200 bytes correspond to 200 characters in ASCII characters"
