### ISSUE TITLE
Feature Request: It appears FDA is warming up for XPT V8, would it be possible to look into exporting that?

### ISSUE THREAD

**Issue by perttolj** [atorus-research/xportr#41]
In the presentation given here https://www.diaglobal.org/en/conference-listing/meetings/2022/04/dia-biostatistics-industry-and-regulator-forum/agenda/07/session-6-yes-you-can-use-r-in-regulatory-submissions?ref=Session6YesYouCanUseRinRegulatorySubmissions  a person from FDA stated the following: 
![image](https://user-images.githubusercontent.com/34157789/175305527-5f3333ff-7c2f-44a4-b207-f11ab04ebae9.png)

This gives hope that V8 would be in the future accepted instead of the very restrictive V5.

The presentation gives some further details as well:
![image](https://user-images.githubusercontent.com/34157789/175306419-0918f473-b8f8-49c4-83c6-b9068070be58.png)

It would be great to confirm this (possibly at a repeat of this presentation https://hopin.com/events/the-r-adoption-series-using-r-in-regulatory-review) and if confirmed, would be very helpful if xportr could optionally produce V8 xpt datasets as well.

**Comment by mstackhouse** [comment]
The route that CDISC has been looking has long been to get away from export files in general. Dataset.XML was a failed experiment because of inflated file sizes specifically but [Dataset.JSON](https://wiki.cdisc.org/display/ODM2/Dataset-JSON) is a successor to that and an initiative that I'm hopeful for, because it's _much_ less verbose than XML. 

From an architecture standpoint, version 8 would be a simple switch with haven under the hood and some minor changes to the checks performed around the datasets, them flipping a parameter on the `haven::write_xpt()` call.
